release:
  title-prefix: 'v'
  initial-version: '0.0.1'
  tag-prefix: 'v'
  commit-note-replacers:
    - replace-prefix: 'feat():'
      new-prefix: 'feature: '
    - replace-prefix: 'fix():'
      new-prefix: 'fix: '
    - replace-prefix: 'docs():'
      new-prefix: 'document: '
    - replace-prefix: 'chore():'
      new-prefix: 'chore: '
    - replace-prefix: 'style():'
      new-prefix: 'style: '
    - replace-prefix: 'refactor():'
      new-prefix: 'refactor: '
    - replace-prefix: 'test():'
      new-prefix: 'test: '
    - replace-prefix: 'wip():'
      new-prefix: 'wip: '
categories:
  - title: 'Features'
    commits:
      - 'feature: '
    changes-prefix: ':sparkles:'
  - title: 'Bug Fixes'
    commits:
      - 'fix: '
    changes-prefix: ':bug:'
  - title: 'Documentation'
    commits:
      - 'document: '
    changes-prefix: ':memo:'
  - title: 'Others'
    commits:
      - 'chore: '
      - 'style: '
      - 'refactor: '
      - 'test: '
      - 'wip: '
    changes-prefix: ':hammer:'
bump:
  default: 'patch'
  major:
    commits:
      - 'breaking:'
  minor:
    commits:
      - 'feature: '
