version: '3.8'

services:
  app:
    container_name: scrape-it
    build:
      context: .
      dockerfile: Dockerfile
    image: scrape-it
    env_file: .env
    ports:
      - "3000:3000"
    restart: unless-stopped
